
device: cuda

training:
  batch_size: 8
  n_epochs: 100000
  snapshot_freq: 10
  snapshot_sampling: true
  resume_training: true

sampling: 
  batch_size: 25
  data_init: false

data:
  dataset: abdomenCT
  image_size: 224
  num_classes: 1
  train_path: path/to/data
  channels: 1
  rescaled: false
  random_flip: false
  num_workers: 4

optim:
  weight_decay: 0.01
  optimizer: AdamW
  lr: 0.0001
  beta1: 0.9
  beta2: 0.999
  amsgrad: false
  eps: 0.00000001
