training:
  batch_size: 8
  n_epochs: 1000
  resume_training: false
  snapshot_freq: 1
  snapshot_sampling: true

sampling: 
  batch_size: 8
  data_init: false

data:
  image_path: "/path/to/data/folder"
  dataset: "landscape"
  image_size: 128
  num_classes: 10
  channels: 3
  rescaled: false
  random_flip: true
  num_workers: 4

optim:
  weight_decay: 0.000
  optimizer: "AdamW"
  lr: 0.0001
  beta1: 0.9
  beta2: 0.999
  amsgrad: false
  eps: 0.00000001
