
device: "cuda"

training:
  batch_size: 4
  n_epochs: 1000
  snapshot_freq: 1
  snapshot_sampling: true
  resume_training: false

sampling: 
  batch_size: 6
  data_init: false
  denoise: true

data:
  dataset: "xray"
  image_size: 256
  num_classes: 1
  image_path: "path/to/xray/image"
  channels: 1
  random_flip: true
  rescaled: false
  num_workers: 4

optim:
  weight_decay: 0.01
  optimizer: "AdamW"
  lr: 0.0001
  beta1: 0.9
  beta2: 0.999
  amsgrad: false
  eps: 0.00000001
